# Site settings
title: "smllrd"
description: A test for Sam Ellard's blog.

author: Sam Ellard
email: ellardsaa@gmail.com
twitter_username: smllrd
github_username: redllamas

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://etcblog.jp" # the base hostname & protocol for your site

google_analytics_id: UA-60126812-4
disqus_id:

# Build settings
include: [_pages]
markdown: kramdown
permalink: /blog/:title

sass:
    style: compressed

exclude: [vendor]

